/**
 * Client-side export helpers. No backend round-trip needed — we already
 * have the full roadmap/cover-letter payload in memory, so we just
 * serialize it into a downloadable text file via a Blob + object URL.
 */

function triggerDownload(filename, content, mime = "text/plain") {
  const blob = new Blob([content], { type: `${mime};charset=utf-8` });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function slugify(text) {
  return (text || "roadmap")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
}

export function downloadRoadmapText(roadmap) {
  const lines = [];
  lines.push(`CAREEROS — 90-DAY ROADMAP`);
  lines.push(`Target role: ${roadmap.target_role}`);
  lines.push(`Generated by: ${roadmap.source === "openai" ? "GPT-4o" : "CareerOS smart template"}`);
  lines.push("");
  lines.push(roadmap.summary);
  lines.push("");
  lines.push("=".repeat(60));
  lines.push("");

  roadmap.weeks.forEach((week, i) => {
    lines.push(`${i + 1}. ${week.week_range} — ${week.focus}`);
    week.tasks.forEach((t) => lines.push(`   • ${t}`));
    lines.push(`   Milestone: ${week.milestone}`);
    lines.push("");
  });

  lines.push("-".repeat(60));
  lines.push("Generated with CareerOS — careeros-demo.example.com");

  triggerDownload(`careeros-roadmap-${slugify(roadmap.target_role)}.txt`, lines.join("\n"));
}

export function downloadCoverLetterText(draft) {
  const lines = [];
  lines.push(`Cover letter — ${draft.job_title} at ${draft.company}`);
  lines.push(`Generated by: ${draft.source === "openai" ? "GPT-4o" : "CareerOS smart template"}`);
  lines.push("");
  lines.push(draft.cover_letter);

  if (draft.resume_bullet_suggestions?.length) {
    lines.push("");
    lines.push("-".repeat(60));
    lines.push("Resume bullet suggestions:");
    draft.resume_bullet_suggestions.forEach((b) => lines.push(`  • ${b}`));
  }

  triggerDownload(`cover-letter-${slugify(draft.company + "-" + draft.job_title)}.txt`, lines.join("\n"));
}
